In [2]:
import pandas as pd

In [5]:
trial_df = pd.read_csv("/home/bily/python/activity_tracker/data/Recovery workout log - barbell weights.csv")

In [6]:
trial_df.head()

,date,exercise,reps,set,mass (lbs),mass (kgs),rest,notes,to failure?
0,25.8.15,calf raise machine,10,3,0,0.0,60.0,60/40 2 legged,yes
1,25.8.15,heel raise squat bar,10,3,0,0.0,60.0,NaN,yes
2,25.8.15,1 leg extension,10,3,45,20.0,60.0,NaN,yes
3,25.8.15,1 leg curl,10,3,30,14.0,60.0,NaN,yes
4,25.8.22,calf raise machine,10,3,0,0.0,60.0,70/30 2 legged,yes

In [8]:
trial_df.loc[trial_df['exercise'].str.contains("dead"), 'mass (lbs)'].max()

253

In [27]:
index = trial_df[trial_df['date'].str.count('\.') == 1].index
index

<>:1: SyntaxWarning: invalid escape sequence '\.'
<>:1: SyntaxWarning: invalid escape sequence '\.'
/tmp/ipykernel_11181/4103893233.py:1: SyntaxWarning: invalid escape sequence '\.'
  index = trial_df[trial_df['column_name'].str.count('\.') == 1].index

Index([167, 170, 171, 172], dtype='int64')

In [39]:
a = "24.03.24"
print(a.replace(".", ''))

240324

In [49]:
def fix_date(value):
    fresh_start = value.replace(".", "").strip().replace(" ", "")
    if len(fresh_start) == 6:
        new_value = fresh_start[0:2] + "." + fresh_start[2:4] + "." + fresh_start[4:6]
    elif len(fresh_start) == 5:
        if fresh_start[0:3] == "258":
            new_value = fresh_start[0:2] + ".0" + fresh_start[2:3] + "." + fresh_start[3:5]
    else:
        new_value = "bugger"
    return new_value

trial_df['column_name'] = trial_df['date'].apply(fix_date)

In [50]:
trial_df[trial_df['column_name'] == 'bugger']

Empty DataFrame
Columns: [date, exercise, reps, set, mass (lbs), mass (kgs), rest, notes, to failure?, fakedate, column_name]
Index: []

In [51]:
trial_df.head()

,date,exercise,reps,set,mass (lbs),mass (kgs),rest,notes,to failure?,fakedate,column_name
0,25.8.15,calf raise machine,10,3,0,0.0,60.0,60/40 2 legged,yes,"[25, 8, 15]",25.08.15
1,25.8.15,heel raise squat bar,10,3,0,0.0,60.0,NaN,yes,"[25, 8, 15]",25.08.15
2,25.8.15,1 leg extension,10,3,45,20.0,60.0,NaN,yes,"[25, 8, 15]",25.08.15
3,25.8.15,1 leg curl,10,3,30,14.0,60.0,NaN,yes,"[25, 8, 15]",25.08.15
4,25.8.22,calf raise machine,10,3,0,0.0,60.0,70/30 2 legged,yes,"[25, 8, 22]",25.08.22

In [26]:
trial_df['date'] = pd.to_datetime(trial_df['column_name'], format='%y.%m.%d')

ValueError: time data "26.01 20" doesn't match format "%y.%m.%d", at position 26. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.